package uk.ac.ebi.uniprot.parser.ffwriter.line;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import uk.ac.ebi.uniprot.domain.Sequence;
import uk.ac.ebi.uniprot.domain.uniprot.factory.UniProtFactory;
import uk.ac.ebi.uniprot.parser.ffwriter.FFLine;
import uk.ac.ebi.uniprot.parser.impl.sq.SQLineBuilder;

public class SQLineBuildTest {
	@Test
	public void test() {
		String sqLine = "SQ   SEQUENCE   504 AA;  54443 MW;  F994A9048C816394 CRC64;\n" + 
				"     MTPTLAALLC LGLSLGPRTH VQAGPFPKPT LWAEPGSVIS WGSPVTIWCQ GSLEAQEYRL\n" + 
				"     DKEGSPEPWD RNNPLEPKNK ARFSIPSITE HHAGRYRCHY YSSAGWSEPS DPLELVMTGA\n" + 
				"     YSKPTLSALP SPVVASGGNM TLQCGSQKGY HHFVLMKEGE HQLPRTLDSQ QLHSGGFQAL\n" + 
				"     FPVGPVNPSH RWRFTCYYYY MNTPRVWSHP SDPLEILPSG VSRKPSLLTL QGPVLAPGQS\n" + 
				"     LTLQCGSDVG YDRFVLYKEG ERDFLQRPGQ QPQAGLSQAN FTLGPVSPSH GGQYRCYGAH\n" + 
				"     NLSSEWSAPS DPLNILMAGQ IYDTVSLSAQ PGPTVASGEN VTLLCQSWWQ FDTFLLTKEG\n" + 
				"     AAHPPLRLRS MYGAHKYQAE FPMSPVTSAH AGTYRCYGSY SSNPHLLSFP SEPLELMVSG\n" + 
				"     HSGGSSLPPT GPPSTPGESL RPRGERGLPQ GSLSLPKDPT PLPSRTGLCP RGSEAGLVKS\n" + 
				"     GGFKAERDVG AQPGGGAGLM WGAR";
		SQLineBuilder builder = new SQLineBuilder();
		String seq="MTPTLAALLCLGLSLGPRTHVQAGPFPKPTLWAEPGSVISWGSPVTIWCQGSLEAQEYRLDKEGSPEPWDRNNPLEPKNKARFSIPSIT"
				+ "EHHAGRYRCHYYSSAGWSEPSDPLELVMTGAYSKPTLSALPSPVVASGGNMTLQCGSQKGYHHFVLMKEGEHQLPRTLDSQQLHSGGFQA"
				+ "LFPVGPVNPSHRWRFTCYYYYMNTPRVWSHPSDPLEILPSGVSRKPSLLTLQGPVLAPGQSLTLQCGSDVGYDRFVLYKEGERDFLQRPG"
				+ "QQPQAGLSQANFTLGPVSPSHGGQYRCYGAHNLSSEWSAPSDPLNILMAGQIYDTVSLSAQPGPTVASGENVTLLCQSWWQFDTFLLTKEGA"
				+ "AHPPLRLRSMYGAHKYQAEFPMSPVTSAHAGTYRCYGSYSSNPHLLSFPSEPLELMVSGHSGGSSLPPTGPPSTPGESLRPRGERGLPQGSLS"
				+ "LPKDPTPLPSRTGLCPRGSEAGLVKSGGFKAERDVGAQPGGGAGLMWGAR";
		Sequence sequence =UniProtFactory.INSTANCE.createSequence(seq);
		FFLine ffLine = builder.build(sequence);
		String resultString = ffLine.toString();
		assertEquals(sqLine, resultString);
	}
}
