/*
SQ   SEQUENCE   256 AA;  29735 MW;  B4840739BF7D4121 CRC64;
     MAFSAEDVLK EYDRRRRMEA LLLSLYYPND RKLLDYKEWS PPRVQVECPK APVEWNNPPS
     EKGLIVGHFS GIKYKGEKAQ ASEVDVNKMC CWVSKFKDAM RRYQGIQTCK IPGKVLSDLD
     AKIKAYNLTV EGVEGFVRYS RVTKQHVAAF LKELRHSKQY ENVNLIHYIL TDKRVDIQHL
     EKDLVKDFKA LVESAHRMRQ GHMINVKYIL YQLLKKHGHG PDGPDILTVK TGSKGVLYDD
     SFRKIYTDLG WKFTPL
*/

lexer grammar SqLineLexer;

SQ: 'SQ';
SEQUENCE: 'SEQUENCE';
AA: 'AA;';
MW: 'MW;';
CRC64: 'CRC64;';

INT: [1-9][0-9]*;
CRCLETTERS :[0-9A-Z]+;
NEWLINE : '\n';
SPACE1 : ' ';
SPACE2 : '  ';
SPACE3 : '   ';
fragment UP_LETTER : [A-Z];

SPACE5 : '     '  -> pushMode(SQ_LETTERS);

mode SQ_LETTERS;
SQLETTER10 : SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER9 :  SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER8 :  SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER7 :  SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER6 :  SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER5 :  SQLETTER SQLETTER SQLETTER SQLETTER SQLETTER ;
SQLETTER4 :  SQLETTER SQLETTER SQLETTER SQLETTER;
SQLETTER3 :  SQLETTER SQLETTER SQLETTER;
SQLETTER2 :  SQLETTER SQLETTER ;
SQLETTER : [ARNDCQEGHILKMFPSTWYVOUBZX];
NEWLINE_SQ:     '\n'     ->type (NEWLINE), popMode;
SPACE1_SQ : ' '    -> type (SPACE1);