package org.uniprot.core.util;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.math.BigDecimal;

import org.junit.jupiter.api.Test;

class Crc64Test {

    @Test
    void testSeq() {
        String seq =
                "MGQARPAARRPHSPDPGAQPAPPRRRARALALLGALLAAAAAVAAARACALLADAQAAARQESALKVLGTDGLFLFSSLDTDQDMYISPEEFKPIAEKLTGSVPVANYEEEELPHDPSEETLTIEARFQPLLMETMTKSKDGFLGVSRLALSGLRNWTTAASPSAAFAARHFRPFLPPPGQELGQPWWIIPGELSVFTGYLSNNRFYPPPPKGKEVIIHRLLSMFHPRPFVKTRFAPQGTVACLTAISDSYYTVMFRIHAEFQLSEPPDFPFWFSPGQFTGHIILSKDATHIRDFRLFVPNHRSLNVDMEWLYGASETSNMEVDIGYVPQMELEAVGPSVPSVILDEDGNMIDSRLPSGEPLQFVFEEIKWHQELSWEEAARRLEVAMYPFKKVNYLPFTEAFDRARAEKKLVHSILLWGALDDQSCUGSGRTLRETVLESPPILTLLNESFISTWSLVKELEDLQTQQENPLHRQLAGLHLEKYSFPVEMMICLPNGTVVHHINANYFLDITSMKPEDMENNNVFSFSSSFEDPSTATYMQFLREGLRRGLPLLQP";
        String seq2 =
                "MGQARPAARRPHSPDPGAQPAPPRRRARALALLGALLAAAAAVAAARACALLADAQAAARQESALKVLGTDGLFLFSSLDTDQDMYISPEEFKPIAEKLTGSVPVANYEEEELPHDPSEETLTIEARFQPLLMETMTKSKDGFLGVSRLALSGLRNWTTAASPSAAFAARHFRPFLPPPGQELGQPWWIIPGELSVFTGYLSNNRFYPPPPKGKEVIIHRLLSMFHPRPFVKTRFAPQGTVACLTAISDSYYTVMFRIHAEFQLSEPPDFPFWFSPGQFTGHIILSKDATHIRDFRLFVPNHRSLNVDMEWLYGASETSNMEVDIGYVPQMELEAVGPSVPSVILDEDGNMIDSRLPSGEPLQFVFEEIKWHQELSWEEAARRLEVAMYPFKKVNYLPFTEAFDRARAEKKLVHSILLWGALDDQSCCGSGRTLRETVLESPPILTLLNESFISTWSLVKELEDLQTQQENPLHRQLAGLHLEKYSFPVEMMICLPNGTVVHHINANYFLDITSMKPEDMENNNVFSFSSSFEDPSTATYMQFLREGLRRGLPLLQP";
        String cString1 = Crc64.getCrc64(seq);
        String cString2 = Crc64.getCrc64(seq2);

        assertEquals("D085928963DE8257", cString1);
        assertEquals("3E88FC97C3DE8249", cString2);
    }

    @Test
    void testSeq2() {
        String seq =
                "MQTFLKGKRVGYWLSEKKIKKLNFQAFAELCRKRGMEVVQLNLSRPIEEQGPLDVIIHKLTDVILEADQNDSQSLELVHRFQEYIDAHPETIVLDPLPAIRTLLDRSKSYELIRKIEAYMEDDRICSPPFMELTSLCGDDTMRLLEKNGLTFPFICKTRVAHGTNSHEMAIVFNQEGLNAIQPPCVVQNFINHNAVLYKVFVVGESYTVVQRPSLKNFSAGTSDRESIFFNSHNVSKPESSSVLTELDKIEGVFERPSDEVIRELSRALRQALGVSLFGIDIIINNQTGQHAVIDINAFPGYEGVSEFFTDLLNHIATVLQGQSTAMAATGDVALLRHSKLLAEPAGGLVGERTCSASPGCCGSMMGQDAPWKAEADAGGTAKLPHQRLGCNAGVSPSFQQHCVASLATKASSQ";
        String cString1 = Crc64.getCrc64(seq);
        BigDecimal bd = Crc64.getCrc64BD(seq);
        String c2 = Long.toHexString(bd.longValue()).toUpperCase();
        assertEquals("E89E2EE11971278E", cString1);
        assertEquals("E89E2EE11971278E", c2);
    }
}
