package uk.ac.ebi.uniprot.domain.uniprot.comments.impl;

import uk.ac.ebi.uniprot.domain.uniprot.EvidencedValue;

import java.util.ArrayList;
import java.util.List;

public class FreeTextImpl {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private List<EvidencedValue> texts;

    public FreeTextImpl() {}

    public List<EvidencedValue> getTexts() {
        if (texts == null)
            texts = new ArrayList<>();
        return texts;
    }

    public void setTexts(List<EvidencedValue> texts) {
        if (texts != null) {
            this.texts = texts;
        } else {
            throw new IllegalArgumentException();
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        final FreeTextImpl evValue = (FreeTextImpl) o;

        if (texts != null && texts.size() > 0 ? !texts
                .equals(evValue.texts) : evValue.texts != null
                        && evValue.texts.size() > 0)
            return false;

        return true;
    }

    /**
     * Returns a hash code value for this object. Method was autogenerated by IntelliJ.
     *
     * @return a hash code value for this object.
     */
    @Override
    public int hashCode() {
        int result = 0;
        result =
                +(texts != null && texts.size() > 0 ? texts
                        .hashCode() : 0);
        return result;
    }

    private long id = 0l;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

}
