package org.uniprot.core.flatfile.tool;



import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.uniprot.core.flatfile.parser.UniProtEntryIterator;
import org.uniprot.core.flatfile.parser.UniProtParserHelper;
import org.uniprot.core.uniprotkb.UniProtKBEntry;



public class SplicedSequenceCalculatorTest {
	static UniProtKBEntry entry;
	@BeforeAll
	 static void setup()throws Exception {
        String filename = "src/test/resources/entryIT/Q03112.dat";
        UniProtEntryIterator iterator = UniProtParserHelper.parseFile(filename, "", "", "", "");
        assertTrue(iterator.hasNext());
        entry = iterator.next();

	}
	@Test
	 void testQ03112_1() {
		String sequence ="MKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLESENDLQEIHTIQECKE"
				+ "CDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKVFTDPSNLQRHIRSQHVGARAHACPEC"
				+ "GKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKHRRFCEGKNHFAAGGFF"
				+ "GQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPASSPVKGLSSTEQTNKSQ"
				+ "SPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLETTSGSDLESDIESDKEK"
				+ "FKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGLQDKKVGALPYPSMFPL"
				+ "PFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPATSQDQPLDLSMGSRSRA"
				+ "SGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPGFLFHPQFQLPDQRTWM"
				+ "SAIENMAEKLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQPYRCKYCD"
				+ "RSFSISSNLQRHVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSSPHSELESTGAILDDKEDAYFTEIRNFIGN"
				+ "SNHGSQSPRNVEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDITGKTGKEPVTSNLHEGNPEDDYEETSALEMS"
				+ "CKTSPVRYKEEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPEELKQPLHRKSKSQAYAMMLSLSDKESLHSTS"
				+ "HSSSNVWHSMARAAAESSAIQSISHV";
		String isoform ="Q03112-1";
		String isoformName ="1";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	
	@Test
	 void testQ03112_3() {
		String sequence ="MRSKGRARKLATNNECVYGNYPEIPLEEMPDADGVASTPSLNIQEPCSPATSSEAFTPKEGSPYKAPIYIPDDIPIP"
				+ "AEFELRESNMPGAGLGIWTKRKIEVGEKFGPYVGEQRSNLKDPSYGWEILDEFYNVKFCIDASQPDVGSWLKYIRFAGCYDQHNL"
				+ "VACQINDQIFYRVVADIAPGEELLLFMKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQ"
				+ "QKLESENDLQEIHTIQECKECDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKVFTDPS"
				+ "NLQRHIRSQHVGARAHACPECGKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTT"
				+ "SSLNKHRRFCEGKNHFAAGGFFGQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHR"
				+ "PPLIPASSPVKGLSSTEQTNKSQSPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVST"
				+ "PSGSDLETTSGSDLESDIESDKEKFKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKY"
				+ "FGSTGLVGLQDKKVGALPYPSMFPLPFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPV"
				+ "PSKPPVTPATSQDQPLDLSMGSRSRASGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEA"
				+ "LKEKYLRPSPGFLFHPQFQLPDQRTWMSAIENMAEKLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCG"
				+ "KIFPRSANLTRHLRTHTGEQPYRCKYCDRSFSISSNLQRHVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSS"
				+ "PHSELESTGAILDDKEDAYFTEIRNFIGNSNHGSQSPRNVEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDIT"
				+ "GKTGKEPVTSNLHEGNPEDDYEETSALEMSCKTSPVRYKEEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPE"
				+ "ELKQPLHRKSKSQAYAMMLSLSDKESLHSTSHSSSNVWHSMARAAAESSAIQSISHV";
		String isoform ="Q03112-3";
		String isoformName ="2";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}

	@Test
	 void testQ03112_4() {
		String sequence ="MILDEFYNVKFCIDASQPDVGSWLKYIRFAGCYDQHNLVACQINDQIFYRVVADIAPGEELLLFMKSEDYPHETMAPD"
				+ "IHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLESENDLQEIHTIQECKECDQVFPDLQSLEKHMLSHTE"
				+ "EREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKQVFTDPSNLQRHIRSQHVGARAHACPECGKTFATSSGLKQHKHIHS"
				+ "SVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKHRRFCEGKNHFAAGGFFGQGISLPGTPAMDKTSM"
				+ "VNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPASSPVKGLSSTEQTNKSQSPLMTHPQILPATQDI"
				+ "LKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLETTSGSDLESDIESDKEKFKENGKMFKDKVSPL"
				+ "QNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGLQDKKVGALPYPSMFPLPFFPAFSQSMYPFP"
				+ "DRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPATSQDQPLDLSMGSRSRASGTKLTEPRKNHV"
				+ "FGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPGFLFHPQFQLPDQRTWMSAIENMAEKLES"
				+ "FSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQPYRCKYCDRSFSISSNLQR"
				+ "HVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSSPHSELESTGAILDDKEDAYFTEIRNFIGNSNHGSQSPRN"
				+ "VEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDITGKTGKEPVTSNLHEGNPEDDYEETSALEMSCKTSPVRYK"
				+ "EEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPEELKQPLHRKSKSQAYAMMLSLSDKESLHSTSHSSSNVWH"
				+ "SMARAAAESSAIQSISHV";
		String isoform ="Q03112-4";
		String isoformName ="4";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}

	@Test
	 void testQ03112_5() {
		String sequence ="MKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLESENDLQEIHTIQECK"
				+ "ECDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKVFTDPSNLQRHIRSQHVGARAHACP"
				+ "ECGKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKHRRFCEGKNHFAAG"
				+ "GFFGQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPASSPVKGLSSTEQT"
				+ "NKSQSPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLETTSGSDLESDIE"
				+ "SDKEKFKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGLQDKKVGALPY"
				+ "PSMFPLPFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPATSQDQPLDLS"
				+ "MGSRSRASGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPGFLFHPQMS"
				+ "AIENMAEKLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQPYRCKYCD"
				+ "RSFSISSNLQRHVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSSPHSELESTGAILDDKEDAYFTEIRNFIG"
				+ "NSNHGSQSPRNVEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDITGKTGKEPVTSNLHEGNPEDDYEETSALE"
				+ "MSCKTSPVRYKEEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPEELKQPLHRKSKSQAYAMMLSLSDKESLH"
				+ "STSHSSSNVWHSMARAAAESSAIQSISHV";
		String isoform ="Q03112-5";
		String isoformName ="5";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	
	@Test
	 void testQ03112_6() {
		String sequence ="MKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLESENDLQEIHTIQECKE"
				+ "CDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKQVFTDPSNLQRHIRSQHVGARAHACPE"
				+ "CGKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKHRRFCEGKNHFAAGGF"
				+ "FGQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPASSPVKGLSSTEQTNKS"
				+ "QSPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLETTSGSDLESDIESDKE"
				+ "KFKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGLQDKKVGALPYPSMFP"
				+ "LPFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPATSQDQPLDLSMGSRSR"
				+ "ASGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPGFLFHPQMSAIENMAE"
				+ "KLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQPYRCKYCDRSFSISSN"
				+ "LQRHVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSSPHSELESTGAILDDKEDAYFTEIRNFIGNSNHGSQSP"
				+ "RNVEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDITGKTGKEPVTSNLHEGNPEDDYEETSALEMSCKTSPVRY"
				+ "KEEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPEELKQPLHRKSKSQAYAMMLSLSDKESLHSTSHSSSNVWH"
				+ "SMARAAAESSAIQSISHV";
		String isoform ="Q03112-6";
		String isoformName ="6";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	@Test
	 void testQ03112_7() {
		String sequence ="MRSKGRARKLATNNECVYGNYPEIPLEEMPDADGVASTPSLNIQEPCSPATSSEAFTPKEGSPYKAPIYIPDDIPIPAE"
				+ "FELRESNMPGAGLGIWTKRKIEVGEKFGPYVGEQRSNLKDPSYGWEILDEFYNVKFCIDASQPDVGSWLKYIRFAGCYDQHNLVAC"
				+ "QINDQIFYRVVADIAPGEELLLFMKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLE"
				+ "SENDLQEIHTIQECKECDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKVFTDPSNLQRH"
				+ "IRSQHVGARAHACPECGKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKH"
				+ "RRFCEGKNHFAAGGFFGQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPAS"
				+ "SPVKGLSSTEQTNKSQSPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLET"
				+ "TSGSDLESDIESDKEKFKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGL"
				+ "QDKKVGALPYPSMFPLPFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPAT"
				+ "SQDQPLDLSMGSRSRASGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPG"
				+ "FLFHPQMSAIENMAEKLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQP"
				+ "YRCKYCDRSFSISSNLQRHVRNIHNKEKPFKCHLCDRCFGQQTNLDRHLKKHENGNMSGTATSSPHSELESTGAILDDKEDAYFTE"
				+ "IRNFIGNSNHGSQSPRNVEERMNGSHFKDEKALVTSQNSDLLDDEEVEDEVLLDEEDEDNDITGKTGKEPVTSNLHEGNPEDDYEE"
				+ "TSALEMSCKTSPVRYKEEEYKSGLSALDHIRHFTDSLKMRKMEDNQYSEAELSSFSTSHVPEELKQPLHRKSKSQAYAMMLSLSDK"
				+ "ESLHSTSHSSSNVWHSMARAAAESSAIQSISHV";
		String isoform ="Q03112-7";
		String isoformName ="7";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	@Test
	 void testQ03112_8() {
		String sequence ="MRSKGRARKLATNNECVYGNYPEIPLEEMPDADGVASTPSLNIQEPCSPATSSEAFTPKEGSPYKAPIYIPDDIPIPAE"
				+ "FELRESNMPGAGLGIWTKRKIEVGEKFGPYVGEQRSNLKDPSYGWEILDEFYNVKFCIDASQPDVGSWLKYIRFAGCYDQHNLVAC"
				+ "QINDQIFYRVVADIAPGEELLLFMKSEDYPHETMAPDIHEERQYRCEDCDQLFESKAELADHQKFPCSTPHSAFSMVEEDFQQKLE"
				+ "SENDLQEIHTIQECKECDQVFPDLQSLEKHMLSHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKHYECENCAKVFTDPSNLQRH"
				+ "IRSQHVGARAHACPECGKTFATSSGLKQHKHIHSSVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKH"
				+ "RRFCEGKNHFAAGGFFGQGISLPGTPAMDKTSMVNMSHANPGLADYFGANRHPAGLTFPTAPGFSFSFPGLFPSGLYHRPPLIPAS"
				+ "SPVKGLSSTEQTNKSQSPLMTHPQILPATQDILKALSKHPSVGDNKPVELQPERSSEERPFEKISDQSESSDLDDVSTPSGSDLET"
				+ "TSGSDLESDIESDKEKFKENGKMFKDKVSPLQNLASINNKKEYSNHSIFSPSLEEQTAVSGAVNDSIKAIASIAEKYFGSTGLVGL"
				+ "QDKKVGALPYPSMFPLPFFPAFSQSMYPFPDRDLRSLPLKMEPQSPGEVKKLQKGSSESPFDLTTKRKDEKPLTPVPSKPPVTPAT"
				+ "SQDQPLDLSMGSRSRASGTKLTEPRKNHVFGGKKGSNVESRPASDGSLQHARPTPFFMDPIYRVEKRKLTDPLEALKEKYLRPSPG"
				+ "FLFHPQFQLPDQRTWMSAIENMAEKLESFSALKPEASELLQSVPSMFNFRAPPNALPENLLRKGKERYTCRYCGKIFPRSANLTRH"
				+ "LRTHTGEQLKNKDLQ";
		String isoform ="Q03112-8";
		String isoformName ="8";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	
	@Test
	public void testQ03112_9() {
		String sequence ="MRSKGRARKLATNNECVYGNYPEIPLEEMPDADGVASTPSLNIQEPCSPATSSEAFTPKEGSPYKAPIYIPDDIPIPAE"
				+ "FELRESNMPGAGLGIWTKRKIEVGEKFGPYVGEQRSNLKDPSYGWEVHLPRSRRVSVHSWLYLGKRSSDVGIAFSQADVYMPGLQCAFLS";
		String isoform ="Q03112-9";
		String isoformName ="9";
		testcalculateSequenceByIsoformId(isoform, sequence);
		testcalculateSequenceByName(isoformName, sequence);
	}
	
	private void testcalculateSequenceByIsoformId(String isoform, String sequence) {
		  String isoSeq = SplicedSequenceCalculator.getSplicedSequenceByIsoId(entry, isoform);
		  assertEquals(sequence, isoSeq);
	}
	private void testcalculateSequenceByName(String isoformName, String sequence) {
		  String isoSeq = SplicedSequenceCalculator.getSplicedSequenceByName(entry, isoformName);
		  assertEquals(sequence, isoSeq);
	}
}
